server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server-git

  cloud:
    config:
      label: master # 配置仓库的分支
      server:
        git:
          uri: https://github.com/liujun19921020/SpringCloudDemo/  # 配置git仓库地址
          searchPaths: ConfigDemo # 配置仓库路径
          username: # 访问git仓库的用户名
          password: # 访问git仓库的用户密码

