spring:
  datasource:
    druid:
      # cs1_db库
      cs1-db:
        url: jdbc:mysql://${cloud.cs1db.common.host}:${cloud.cs1db.common.port}/${cloud.cs1db.common.database}?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
        driver-class-name: com.mysql.jdbc.Driver
        username: ${cloud.cs1db.common.username}
        password: ${cloud.cs1db.common.password}
        initialSize: 5
        minIdle: 5
        maxActive: 20
      # cs2_db库
      cs2-db:
        url: jdbc:mysql://${cloud.cs2db.common.host}:${cloud.cs2db.common.port}/${cloud.cs2db.common.database}?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
        driver-class-name: com.mysql.jdbc.Driver
        username: ${cloud.cs2db.common.username}
        password: ${cloud.cs2db.common.password}
        initialSize: 5
        minIdle: 5
        maxActive: 20
  cache:
    type: REDIS

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.lj.scmusteritemdemo.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true